from panda3d.core import BitMask32

# # Camera settings
# INITIAL_CAMERA_POS = (4.7, -16.2, 13.1)
# INITIAL_CAMERA_ROT = (52.1, -39.5, 0.0)  # Heading, Pitch, Roll
INITIAL_CAMERA_POS = (-2.97, 16.9, 83.53)
INITIAL_CAMERA_ROT =   (0, -90, 0)
CAMERA_FOV = 90
CAMERA_BASE_SPEED = 0.5
CAMERA_SPRINT_MULTIPLIER = 2.0
MOUSE_SENSITIVITY = 0.2

# Simulation settings
TIME_SCALE = 1
PHYSICS_STEP = 1 / 60.0
RENDER_FRAME_INTERVAL = 1.0 / 60.0
GRAVITY = -9.81
NO_MODEL_CACHE = False

# Map settings
MAP_PATH = "env/assets/de_dust_2.fbx"
WAYPOINT_DATA_PATH = "env/assets/WaypointDust2Verified_p3d_clean_verified.json"
MAP_POSITION = (0, 0, 3)
# MAP_SCALE = 0.00017
COORDINATE_SCALE = 0.01905
MAP_SCALE = COORDINATE_SCALE / 100
MAP_ROTATION = (90, 0, 0)

# Lighting
DIRECTIONAL_LIGHT_COLOR = (0.6, 0.6, 0.6, 1)
DIRECTIONAL_LIGHT_POS = (133, 36, 275)
DIRECTIONAL_LIGHT_ROT = (60, -54, 0)
AMBIENT_LIGHT_COLOR = (0.2, 0.2, 0.2, 1)

# Agent settings
AGENT_MODEL_PATH = "env/assets/agent.glb"
AGENT_SCALE = 0.6
AGENT_HITBOX_RADIUS = 0.13
AGENT_HITBOX_HEIGHT = 1.3
AGENT_HITBOX_MARGIN = 0.05
AGENT_MAX_HEALTH = 100
AGENT_MOVEMENT_SPEED = 4.7625  # holding knife speed = 250 hammer units / sec = 4.7625 m/s
ENABLE_AGENT_SHOOTING = True
ENABLE_BOMB_ACTIONS = True  
TARGET_REACH_DISTANCE_THRESHOLD = AGENT_HITBOX_RADIUS
TARGET_REACH_DISTANCE_THRESHOLD_HEIGHT = 0.15
# INITIAL_HEIGHT_OFFSET = 0.5
INITIAL_HEIGHT_OFFSET = AGENT_HITBOX_HEIGHT / 2 + AGENT_HITBOX_RADIUS
AGENT_JUMP_HEIGHT_THRESHOLD = 0.35
AGENT_JUMP_SPEED = 4.3
AGENT_MAX_JUMP_HEIGHT = 2.0
AGENT_MAX_SLOPE_DEG = 60
STUCK_AGENT_TICK_THRESHOLD = 30
STOP_ACTION_TICK = int(0.5 / PHYSICS_STEP) # data has 0.5s sample rate
# Physics and Collision Settings
COLLISION_BITMASK_ENVIRONMENT = BitMask32.bit(0)
COLLISION_BITMASK_AGENTS = BitMask32.bit(1)
TERRORIST_COLOR = (222/255, 155/255, 53/255, 1)
COUNTER_TERRORIST_COLOR = (93/255, 121/255, 174/255, 1)
DEAD_AGENT_COLOR = (1, 0, 0, 1)
BOMB_COLOR = (245/255, 100/255, 100/255, 1)


# Game Settings
GAME_TIME_LIMIT = 115 # seconds
# GAME_TIME_LIMIT = 5 # seconds
GAME_TIME_BOMB_EXTENSION = 40 # seconds
BOMB_NEAR_DISTANCE_THRESHOLD = 2
STOP_ACTION_INDEX = 8
ENABLE_LOGGING = True
LOG_FOLDER = "logs_damage"
LOG_FREQUENCY = 1/4 # twice per second
DAMAGE_MODEL_FREQUENCY = 1/2 # once per second

# Debug Visualization Settings
DEBUG_LINE_THICKNESS = 2.0
DEBUG_WAYPOINT_COLOR = (0, 0, 1, 1)  # Blue
DEBUG_WAYPOINT_SIZE = 0.03
DEBUG_UNIDIRECTIONAL_EDGE_COLOR = (1, 0, 0, 1)  # Red
DEBUG_UNIDIRECTIONAL_EDGE_THICKNESS = 0.3
DEBUG_BIDIRECTIONAL_EDGE_COLOR = (0, 1, 0, 0.3)  # Green
DEBUG_BIDIRECTIONAL_EDGE_THICKNESS = 0.3
DEBUG_ARROW_SIZE = 0.2
DEBUG_AGENT_PATH_COLOR = (1, 0, 0, 1)  # Red
DEBUG_AGENT_PATH_THICKNESS = 3.0
DEBUG_HITBOX_COLOR = (1, 1, 0, 1)  # Yellow
MINIMAP_IMAGE_PATH = "env/assets/de_dust2.png"
MINIMAP_RATIO = 0.4
MINIMAP_DOT_SIZE = 0.02
MINIMAP_DOT_TEXTURE_PATH = "env/assets/white_dot.png"
SHOW_TRACE = False

# NN Model Settings
DAMAGE_INDICATOR_PREDICTOR_MODEL_PATH = "models/train-di_20250328-183510_y5vpxd"
DAMAGE_OUTCOME_GENERATOR_MODEL_PATH = "models/train-vae_20250321-040316_upf4hz"

# Spectator Mode Settings
SPECTATOR_BASE_SPEED = 10.0
SPECTATOR_SPRINT_MULTIPLIER = 2.5
SPECTATOR_MOUSE_SENSITIVITY = 0.1

# Window Properties
WINDOW_PROPERTIES = {
    'cursor_hidden': True,
    'mouse_mode': 'relative'
}